declare namespace NodeJS {
  interface ProcessEnv
    extends Record<
      | "NEXT_PUBLIC_RECAPTCHA_SITE_KEY"
      | "NEXT_PUBLIC_API_BASE_URL"
      | "NEXT_PUBLIC_SIGNUP_ENDPOINT"
      | "NEXT_PUBLIC_EMAIL_VERIFICATION_ENDPOINT"
      | "NEXT_PUBLIC_FORGOT_PASSWORD_ENDPOINT"
      | "NEXT_PUBLIC_INIT_PASSWORD_RESET_ENDPOINT"
      | "NEXT_PUBLIC_RESET_PASSWORD_ENDPOINT"
      | "NEXT_PUBLIC_LOGIN_ENDPOINT"
      | "NEXT_PUBLIC_ACCOUNTS_ENDPOINT"
      | "NEXT_PUBLIC_NEW_ACCOUNT_ENDPOINT",
      string
    > {}
}
